import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Dither from "../components/Dither/Dither";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Turborepo",
	description: "Generated by create turbo",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<div className={"absolute top-0 left-0 h-full w-full z-0 opacity-40"}>
					<Dither
						waveColor={[0.1, 0.1, 0.1]}
						disableAnimation={false}
						enableMouseInteraction={true}
						mouseRadius={0.1}
						colorNum={2.3}
						waveAmplitude={0.1}
						waveFrequency={2}
						waveSpeed={0.05}
					/>
				</div>
				<main
					className={
						"relative h-screen w-screen flex flex-col items-center justify-center"
					}
				>
					{children}
				</main>
			</body>
		</html>
	);
}
